### ISSUE TITLE
Troca de cores

### ISSUE THREAD

**Issue by victor-freire** [portinariui/portinari-angular#1]
Saudações. prezados

Há a possibilidade de troca das cores do Framework?

**Comment by jhonyeduardo** [comment]
Olá Victor,

Estamos discutindo a melhor forma de disponibilizar a customização do tema.

Em brave teremos um documento no portal do Portinari, explicando o passo a passo.

Qualquer dúvida estamos a disposição.

**Comment by indeer** [comment]
Olá Jhony,
Tem alguma previsão de data para essa possibilidade?

**Comment by paulogabrielfs** [comment]
@victor-freire é possível instalar o tema de cores antigo do THF, deixa o PO com a mesma cara que o THF tinha, foi a minha solução por enquanto para o projeto não ficar branco e rosa :)

**Comment by jhonyeduardo** [comment]
Pessoal,

Existe a possibilidade de fazer um fork do portinari-style e adequar com as cores desejadas.

Nas próximas semanas inciaremos um estudo referente a isto.

**Comment by danielsilvalima1996** [comment]
**Boa tarde, pessoal.**

houve algum avanço em relação a issue?

Obrigado!

**Comment by portinari-dev** [comment]
Vamos liberar essa semana um documento sobre isso.

**Comment by jhosefmarks** [comment]
Vamos liberar um documento essa semana sobre o assunto.
