### ISSUE TITLE
Integração

### ISSUE THREAD

**Issue by AdrianEPVendrametto** [portinariui/portinari-angular#104]
Boa tarde, 
Sabem me informar como fazer a chamada de telas em Portinari pelos Menus do Protheus? Por exemplo, ao chamar um relatório MATR..., ele abrir esse relatório na tela do Portinari.

**Comment by jhonyeduardo** [comment]
Boa tarde Adrian

O Portinari é uma biblioteca de componentes para Angular, essas informações você deve verificar com o framework do Protheus.

Qualquer dúvida estou a disposição.
