### ISSUE TITLE
Binding da propriedade name - Dynamic Forms - Lookup

### ISSUE THREAD

**Issue by isiqueira** [portinariui/portinari-angular#105]
No componente Dynamic Form, quando adicionado um componente Lookup a propriedade name informada não é respeitada.

Verifiquei o arquivo po-dynamic-form-fields.component.html na linha 107, não está sendo feito o binding com a variável e sim atribuindo valor a propriedade name.
PS: há alguma documentação sobre como abrir uma PR?

**Comment by jhonyeduardo** [comment]
Boa tarde @isiqueira 

Analisamos e isto ocorre realmente,
Vamos adicionar este item em nosso backlog para uma correção futura.

Temos sim, veja o documento [CONTRIBUTING](https://github.com/portinariui/portinari-angular/blob/master/CONTRIBUTING.md#pull-requests)

Qualquer dúvida estamos a disposição.

**Comment by isiqueira** [comment]
Obrigado @jhonyeduardo. Parabéns aos envolvidos pelo ótimo projeto.

**Comment by isiqueira** [comment]
@jhonyeduardo como era uma mudança simples, eu tomei a liberdade de mandar uma PR com a mudança, me desculpe caso não tenha seguido as regras.

**Comment by jhonyeduardo** [comment]
@isiqueira Excelente iniciativa!

Vamos revisar a sua PR e qualquer coisa entramos em contato, mas creio que seja realmente o que voce fez,

Obrigado pela contribuição

**Comment by jhonyeduardo** [comment]
Parabéns pela primeira contribuição aprovada!!

Esperamos que possa sempre contribuir conosco!

Abraço.
