### ISSUE TITLE
Possibilitar atribuir valores a input de datapicker, select, etc

### ISSUE THREAD

**Issue by caio-passarelli** [portinariui/portinari-angular#106]
Boa tarde, 

Para facilitar o preenchimento de formulários gostaria de solicitar a possibilidade de preencher campos como "po-select" e "po-datapicker" passando valores.
É possível "settar" valores no select comum do html. Se o "po-select" tivesse uma diretiva que permitisse fazer isso iria facilitar bastante.
Hoje para atualizar um formulários eu tenho 2 hipóteses: 
- Uma delas é fazer na mão um select comum e copiar todo o css do portinari
- Solicitar toda hora que o usuário preencha novamente esses campos estilizados.  

Agradeço desde já. 
Caio Passarelli
Mustti

**Comment by jhonyeduardo** [comment]
Boa tarde Caio,

Verificou nosso Portal?

Veja o exemplo:
"Portinari Select - Customer registration"
https://portinari.io/documentation/po-select?view=web

Você esta atribuindo um model para o componente? No Angular temos duas possibilidades, via [template-driven](https://angular.io/guide/forms) ou [Reactive Form](https://angular.io/guide/reactive-forms)

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Issue fechada por falta de interação.
