### ISSUE TITLE
Lookup busca de processos não listam dados po-page-scheduler

### ISSUE THREAD

**Issue by jeterson** [portinariui/portinari-angular#119]
Meu endpoint `http://localhost:8080/schedulers/processes?page=1&pageSize=10&search=` 
retorna os dados no seguinte formado, seguindo a especificação que diz na documentação do component: 
`[{"processID":"IMPORTACAO_FUNCIONARIO","description":"Importar Funcionários"}]`

No entanto o Lookup de seleção de processos não lista os dados nem as colunas desse resultado da `API`. A renderização dessa tela pode ser vista abaixo.

Não possui as definições de colunas e nem os dados. Não sei se isso precisa ser definido em algum lugar do componente, mas também não está indicado na documentação como isso é definido. Por favor, se precisa definir algo pra funcionar, como e onde eu defino a tabela do lookup para que seja possível eu selecionar os dados ?

Versão: 1.12.0
![scheduler PO](https://user-images.githubusercontent.com/23269618/66748143-717a1300-ee54-11e9-8a6e-346e6b8336d6.PNG)

**Comment by RafaellyG** [comment]
Ola Jeterson.

Você pode visualizar na [documentação do lookup ](https://portinari.io/documentation/po-lookup) a propriedade `p-columns`, caso ela não seja definida as colunas são selecionadas automaticamente de acordo com o serviço (o exemplo basic na tab de `Exemplos`).

Caso o problema continue preciso das seguintes informações para descobrir o que acontece:
- Arquivo .html e .ts referente ao lookup
- Resposta do endpoint (pode ser um print do network do navegador)

Qualquer dúvida estou a disposição 😄

**Comment by jeterson** [comment]
Então, segundo sua informação, as colunas do lookup deveria ser criada automaticamente, porém não foi criada e nem carregou os dados no endpoint.

Meu Html é simples, conforme está na documentação
```
<po-page-job-scheduler [p-service-api]="serviceUrl" p-title="Agendador de Processo">

</po-page-job-scheduler>
```
```
get serviceUrl() {
    return environment.baseApiUrl + '/schedulers';
  }
```
Pelo que eu entendi, ao abrir o modal de pesquisa, deveria listar os processos que retorna no endpoint.

Estou me orientando por essa doc: https://portinari.io/documentation/po-page-job-scheduler
![resposta-endpoint](https://user-images.githubusercontent.com/23269618/66830800-5aa2f180-ef24-11e9-8e5d-7564299f4a23.png)
![resposta-endpoint 2](https://user-images.githubusercontent.com/23269618/66830817-60003c00-ef24-11e9-81c4-65ddca07d685.png)

**Comment by RafaellyG** [comment]
Ola Jeterson!

Identifiquei que temos uma falha em nossa documentação.

Fiz um teste com uma API local e o objeto esperado para retorno é `items: [{"processID":"IMPORTACAO_FUNCIONARIO","description":"Importar Funcionários"}]`.

Você poderia testar e retornar se deu certo para você também?

Aguardo sua resposta e logo após vou encaminhar sua issue para melhoria em nossa documentação.

**Comment by jeterson** [comment]
Opa, Obrigado pelo retorno
Dessa forma, com esse objeto funcionou.
