### ISSUE TITLE
Documentação do componente Input

### ISSUE THREAD

**Issue by Smmartinez** [portinariui/portinari-angular#125]
Na documentação do componente Input existe a chave  t-mask="string", mas não deveria ser p-maks?
Estava tentando utilizar t-mask e não estava colocando a mascara mudei para p-mask e consegui, é isso mesmo?
Não sei se é por aqui esse tipo de solicitação.

**Comment by jhosefmarks** [comment]
Boa tarde @Smmartinez, correção realizada em nosso portal.
