### ISSUE TITLE
Bug no po-chart com valores zerados.

### ISSUE THREAD

**Issue by robsonolivesa** [portinariui/portinari-angular#128]
Passos para reproduzir:
1. Acessar a página https://portinari.io/documentation/po-chart?view=web 
2. No exemplo, incluir uma série com valor zerado

#### Qual o comportamento atual?
O gráfico fica "piscando"

#### Que comportamento você esperava ver?
Gráfico com valores vazios.

#### Ambiente

- Portinari: 1.12
- Angular: 8.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by RafaellyG** [comment]
Ola Robson!

Encaminhei este bug para nosso backlog.

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Item finalizado, será liberado na release de hoje.
