### ISSUE TITLE
Sugestão de melhoria - Permitir passagem de templates no componente de toolbar

### ISSUE THREAD

**Issue by dovalgomes** [portinariui/portinari-angular#134]
Prezados, gostaria de sugerir uma melhoria para que seja possível o envio/customização de templates dentro do componente po-toolbar. De modo que eu consiga trabalhar com uma search-bar ou outro componente de acordo com a minha necessidade.

**Comment by RafaellyG** [comment]
Ola Doval!

Encaminhei sua sugestão para análise de nosso PO.

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Olá @dovalgomes, pode nos dar um exemplo mais prático de onde seria aplicado o template?

**Comment by dovalgomes** [comment]
Olá @jhosefmarks , a ideia na verdade seria conseguir customizar os icones do componente, dando a eles um comportamento parecido com a po-toolbar, porem percebi que posso utilizar a toolbar como header então acredito que não há a necessidade de tal customização.
