### ISSUE TITLE
Envio de informações customizadas

### ISSUE THREAD

**Issue by likid** [portinariui/portinari-angular#137]
Pessoal, no template Page Dynamic Table, ao definir o endpoint ou ao colocar o component no template, teria como adicionar a possibilidade de enviar um campo ou uma informação customizada ao fazer requisições ao endpoint. Peço isso pois da forma que está documentada não há como enviar informações de autenticação para o endpoint e com isso não é possível distinguir quais informações serão retornadas.

**Comment by jhosefmarks** [comment]
Boa tarde @likid,

Você pode criar uma interceptor na sua aplicação, onde a mesma injeta no cabeçalho da sua requisição as informações necessárias sobre autenticação, como por exemplo um token.

**Comment by likid** [comment]
@jhosefmarks fiz a implementação do interceptor aqui, mas não funcionou com a requisição do Page Dynamic Table. Você teria um exemplo?

**Comment by jhosefmarks** [comment]
Você adicionou o interceptor no mesmo módulo que está seu Page Dynamic Table?

Você poderia subir seu exemplo aqui?

https://stackblitz.com/fork/portinariui

**Comment by likid** [comment]
@jhosefmarks realmente era o local que eu havia adicionado o interceptor. Agora funcionou. Vou encerrar esta issue. Muito obrigado pelo apoio.
