### ISSUE TITLE
Sugestão de melhoria PoPageDynamicTable

### ISSUE THREAD

**Issue by likid** [portinariui/portinari-angular#139]
Neste componente há um campo para pesquisa que ao ser digitado e submetido para o endpoint, é gerado uma querystring contendo search=<texto digitado> para que este texto seja procurando em todos os campos, porém, não é enviado na requisição a lista de campo contidos atualmente no componente, forçando o programador a pesquisar em todos os campos possíveis ou pesquisar em campos "hard coded", o que não é o ideal. Então seria interessante de alguma forma, passar para o endpoint quais os campos estão sendo visualizados atualmente, até mesmo porque o campo que deve ser ordenado já é enviado.
Existe o plugin para jQuery chamado DataTables que ao habilitar o processamendo server-side já faz essa passagem de parametros como eu sugeri. https://datatables.net/manual/server-side

**Comment by jhosefmarks** [comment]
Olá @likid,

Sua API deveria entender que se não foi enviado nenhum campo específico, o mesmo deve usar alguma configuração default ao invés de pesquisar em todos. Hoje se você usar a busca avançada desse template, o mesmo envia cada campo que foi usado pelo usuário, sendo assim, entendo que essa funcionalidade que você esta pedindo é uma atribuição da API e não do componente em si.

**Comment by likid** [comment]
Jhosef, a API precisa saber em qual campo pesquisar o texto que foi enviado. Na busca avançada funciona perfeitamente, pois é enviado o campo e o valor a ser pesquisado, mas na busca rápida é enviado apenas o valor e a ordenação do resultado, a API precisa saber em quais campos pesquisar até mesmo para não confundir o usuário. A exemplo do datatables que pesquisa em todos os campos visíveis, então se em uma tabela você está vendo os campos
 Nome do Cliente | Cidade         
-----------------|----------------
 João            | São Paulo     
 José            | Belo Horizonte
Paulo           | Rio de Janeiro 

e pesquisar por Paulo, ao submeter, a API vai terá que retornar o cliente com nome Paulo e o João porque é da cidade de São Paulo, mas para fazer isso sem filtrar todos os campos da tabela, a API precisa saber quais campos foram definidos no componente, que seria o p-fields.

**Comment by jhosefmarks** [comment]
@likid os campos exibidos no table não estão necessariamente vinculados a pesquisa rápida, essa é uma associação que você está impondo a sua página, pois a API pode usar os campos visíveis ou não, da mesma forma que ela não precisa necessariamente usar todos os fields visíveis para efetuar a pesquisa, por exemplo, se você tivesse um campo de status nessa sua tabela, poderia não ser viável para o usuário usar a pesquisa rápida para pesquisar por inativo/ativo/etc... pois se tratando de um sistema que tenha tradução os valores serão diferentes, entre outros casos.

De novo, sua API deve saber como tratar a pesquisa quando a mesma não receber uma lista específica de fields.

Se você está fixando no seu fonte os campos que serão exibidos na página (table), você pode fixar esses campos como default na sua pesquisa rápida na API (a abordagem mais rápida, porem limitada).

Se você passa os fields dinamicamente para sua página (p-service-api) ou alguma chamada no ngOnInit da sua página e carrega os fields de algum endPoint, você pode usar a mesma lógica para a sua API, verificar qual a configuração dos fields e fazer a pesquisa.

**Comment by likid** [comment]
Entendi, mas a minha sugestão era fazer a table funcionar como no datatables que quando é feito uma chamada ao endpoint é passado todas as configurações atuais da tabela, incluindo a lista de campos.

**Comment by jhosefmarks** [comment]
@likid para o template page dynamic table, não faz sentido incluir essa funcionalidade já que existem outras forma de você chegar ao resultado esperado, como já foi explicado anteriormente, e se cada vez que incluirmos algo novo no template ter que adicionar a requisição antes de enviar para o servidor isso mais tarde vai ficar inviável para o componente, a ideia é manter as requisições mais simples possíveis.

Obrigado pela contribuição.
