### ISSUE TITLE
Redirecionar para pagina utilizando o componente po-page-login

### ISSUE THREAD

**Issue by Smmartinez** [portinariui/portinari-angular#156]
Boa tarde! Estou utilizando o componente po-page-login mas não consigo direcionar para outra pagina após a validação de usuário e senha.
Meu componente esta assim
 <po-page-login
  [p-literals]="customLiterals"
  [p-loading]="loading"
  [p-password-errors]="passwordErrors"
  [p-login-errors]="loginErrors"
  (p-login-submit)="checkLogin($event)"
  >
Como faço para direcionar?
Desculpa sei que é uma pergunta de iniciante, mas já tentei de tudo.

Att
Sergio Martinez

**Comment by rmarmitt** [comment]
> Boa tarde! Estou utilizando o componente po-page-login mas não consigo direcionar para outra pagina após a validação de usuário e senha.
> Meu componente esta assim
> <po-page-login
> [p-literals]="customLiterals"
> [p-loading]="loading"
> [p-password-errors]="passwordErrors"
> [p-login-errors]="loginErrors"
> (p-login-submit)="checkLogin($event)"
> 
> > 
> 
> Como faço para direcionar?
> Desculpa sei que é uma pergunta de iniciante, mas já tentei de tudo.
> 
> Att
> Sergio Martinez

Sérgio, como você está fazendo a troca de páginas atualmente? Utilizando o [Angular Router](https://angular.io/guide/router)?

Se sim, basta validar o login e fazer o redirecionamento pelos métodos padrões

**Comment by nicoleoliveira** [comment]
Você pode estar fazendo isso de duas formas:

1) Utilizando o evento `p-login-submit`:
nele você pode passar o método que você irá utilizar para validar se o login está correto ou não. 
E então dentro deste método você pode utilizar o Angular Router para poder fazer o redirecionamento para outra rota, como o @rmarmitt  comentou :)

Tem um exemplo de como utilizar ele dentro do sample [Portinari Page Login - Human Resources](https://portinari.io/documentation/po-page-login)

2) Utilizando um endpoint e colocando ele na propriedade `p-authentication-url`:
o template de login irá enviar uma requisição para este endpoint utilizando o método POST.

Também tem um exemplo de como utilizá-lo no sample [Portinari Page Login - Automatic Service
](https://portinari.io/documentation/po-page-login)

**Comment by Smmartinez** [comment]
Bom dia! Desculpa a demora em responder... Na verdade eu estava meio confuso com a questão das rotas, mas tive ajuda no FLUIG, e o que eu estava fazendo era montar a tela de login no APP principal, e depois recebi a orientação para separar a tela de login em um componente separado e desta forma consegui usar o componente de login.
Agora estou pegando o jeito das rotas e esta ficando mais fácil...
Mas mesmo assim obrigado pelas dicas de vocês.
