### ISSUE TITLE
PoUpload e Firebase

### ISSUE THREAD

**Issue by jeterson** [portinariui/portinari-angular#162]
É possível usar o PoUpload com o firebase? 

Ou se não for possível no momento, quais são os planos para o futuro ?

**Comment by jhosefmarks** [comment]
Olá @jeterson, 

Se o firebase estiver preparado para receber a requisição de upload vai funcionar, agora se precisa ser enviado os dados de outra maneira você pode criar uma rotina para envio dos arquivos que foram incluídos no componente.

Atualmente nós não temos intenção de "amarrar" o componente a um serviço específico pois os componentes serão sempre tratados de forma agnóstica.

**Comment by jhosefmarks** [comment]
Olá @jeterson, 

Se o firebase estiver preparado para receber a requisição de upload vai funcionar, agora se precisa ser enviado os dados de outra maneira você pode criar uma rotina para envio dos arquivos que foram incluídos no componente.

Atualmente nós não temos intenção de "amarrar" o componente a um serviço específico pois os componentes serão sempre tratados de forma agnóstica.

**Comment by jeterson** [comment]
Sim, no caso, é isso mesmo que to falando, pelo que entendi do componente, ele recebe uma URL que precisa receber um POST com um arquivo para o servidor, e nem sempre vamos enviar arquivo dessa forma. No componente PoUpload, não tem como eu personalizar por exemplo o envio, antes dele mandar automaticamente a requisição, ou talvez eu nao tenha achado a forma de fazer isso.
Por exemplo, ter um evento ao clicar no botão, e pegar o arquivo pra fazer algo com ele(enviar ao firebase por exemplo). 
O componente nem habilita o botão se eu não passar uma URL. 

No caso para o firebase, eu nao precisaria informar uma URl, apensas um evento para pegar o arquivo e criar a rotina de envio pra ele, para onde eu quiser. Não consegui ver uma forma de fazer isso com o componente atualmete

**Comment by jhosefmarks** [comment]
@jeterson você consegue fazer isso escondendo o botão de envio (`p-hide-send-button`) e pegando o model do componente e fazendo a implementação do envio da forma que você precisa, para a url como ela não vai ser usada pelo componente, você pode passa um '/' só para manter o botão habilitado.

Veja se assim você consegue chegar no resultado que você deseja.

**Comment by jhosefmarks** [comment]
Issue será fechada:

ISSUES SEM INTERAÇÃO POR MAIS DE 35 DIAS.
