### ISSUE TITLE
Validação do TsLint

### ISSUE THREAD

**Issue by Smmartinez** [portinariui/portinari-angular#163]
Galera estou rodando o tslint do portinari e esta acusando o seguinte erro:
Review this potentially hardcoded credential.
Verificando a linha o que tenho nela é isso:
passwordPlaceholder: 'Digite sua senha',
É do componente PoPageLoginLiterals.
Por que ocorre esse erro?

**Comment by jhosefmarks** [comment]
Boa tarde @Smmartinez,

Use o comando `npm run lint` para executar a tarefa de lint no repositório.

**Comment by jhosefmarks** [comment]
Olá @Smmartinez,

Você está rodando o tslint no nosso repositório ou no seu projeto?

Se for em nosso repositório tente o comando `npm run lint`.

**Comment by Smmartinez** [comment]
Olá, @jhosefmarks Estou rodando no meu projeto.

**Comment by jhosefmarks** [comment]
@Smmartinez você consegue separar o código de exemplo que está gerando o problema e subir uma aplicação no [StackBlitz](https://stackblitz.com/fork/portinariui) ou compartilhar um repositório para que a gente consiga testar?

**Comment by jhosefmarks** [comment]
@Smmartinez eu consegui testar o que você reportou, isso ocorre por que o tslint acha que você está colocando a senha dentro do seu código pois a propriedade tem como parte do nome a palavra chave "password".

Para que o tslint ignore essa linha adicione a seguinte marcação:

```ts
// tslint:disable-next-line:no-hardcoded-credentials
passwordPlaceholder: 'Digite sua senha',
```

Com isso o tslint vai passar a validar seu código.

**Comment by Smmartinez** [comment]
Show de bola... com isso funcionou... Obrigado!
