### ISSUE TITLE
PoTable + ngTemplate com comportamento inesperado

### ISSUE THREAD

**Issue by rmarmitt** [portinariui/portinari-angular#164]
Bom dia! 

Talvez eu esteja montando algo errado, peço que confiram o código primeiramente. Mas o comportamento não é o esperado.

Reprodução no StackBlitz: https://portinariui-bryzgz.stackblitz.io
Código fonte no StackBlitz: https://stackblitz.com/edit/portinariui-bryzgz

#### Passos para reproduzir:

1. Abra a última linha da tabela. Apenas o campo "Controla Compra" estará ativo.
2. Abra a linha intermediária da tabela. Observe que, ao abri-lá, o valor "Controla Venda" da última linha recebe o valor da linha intermediária.
3. Abra a primeira linha da tabela. Todos os demais valores assumem o que está definido na primeira linha.

#### Qual o comportamento atual?

o ngModel está recebendo o valor da última linha expandida, não respeitando o rowItem específico.

#### Que comportamento você esperava ver?

Ao expandir, os valores devem ser os específicos daquela linha da tabela.

#### Ambiente

- Portinari: v1.14.0
- Angular: 8.0.6
- Browser(s): Chrome 77
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro

**Comment by jhosefmarks** [comment]
Olá @rmarmitt, a tag `form` também precisa estar dentro do `ng-template`.

Altere isso que seu template vai ser comportar do jeito correto.

**Comment by rmarmitt** [comment]
Olá @jhosefmarks 

Ops! Gafe minha. Realmente corrigiu. Obrigado :)
