### ISSUE TITLE
Valid nos campos do Dynamic Form

### ISSUE THREAD

**Issue by caiadofelipe** [portinariui/portinari-angular#166]
Boa tarde.

Gostaria de saber se existe alguma maneira de fazer validações específicas nos campos que adicionamos no p-fields <PoDynamicFormField>.

Se não existir, teria como incluir essa funcionalidade?

Att,

**Comment by likid** [comment]
@caiadofelipe , a forma que eles indicam no caso do dynamicform é via o (p-form), mas neste caso eu não acho interessante subscrever a todos os eventos. Aqui eu aproveitei que o portinari é open souce e montei uma construção de formulário dinamica igual ao dynamicform porém adicionando particularidades minhas, dessa forma criei um meio de explorar melhor cada componente.

**Comment by jhosefmarks** [comment]
@caiadofelipe, estamos trabalhando na melhoria desse componente, na próxima sprint do time teremos uma forma de você validar os fields do form dynamic, tanto no seu código como de forma remota disparando requisições para um end-point.

Acompanhe nossos release notes que em breve teremos novidades!

Obrigado pela contribuição!

**Comment by caiadofelipe** [comment]
Obrigado @jhosefmarks  pelo retorno.

Com esta funcionalidade acredito que o componente fique bem completo e sua utilização será muito mais abrangente.

Abraço,

**Comment by jhosefmarks** [comment]
OK!

**Comment by jhosefmarks** [comment]
@caiadofelipe funcionalidade liberada na versão [v1.20.0](https://github.com/portinariui/portinari-angular/blob/master/CHANGELOG.md#1200-2019-12-13).

PR #197
