### ISSUE TITLE
Sugestão PoUpload

### ISSUE THREAD

**Issue by likid** [portinariui/portinari-angular#169]
Atualmente o PoUpload ao enviar os arquivos, faz um post com content type multipart/form-data que é a forma padrão para envio de arquivos via http. Porém ao utilizar um backend rest e principalmente se for no protheus, não temos como manipular esta requisição. Gostaria de sugerir então que houvesse a opção do PoUpload para enviar os arquivos dentro de um json codificados com base64. Sei eu isso impacta no tamanho dos dados que serão transmitidos, porém facilitaria a vida de quem está utilizando uma api restful.

**Comment by jhosefmarks** [comment]
@likid nesse caso você precisa fazer isso manualmente, você pode desabilitar o envio automático do componente e/ou esconder o botão de envio e pegar o arquivo no model e fazer o envio da forma que você precisa.

**Comment by fabiomr78** [comment]
teste integracao

**Comment by likid** [comment]
@jhosefmarks mas fazendo dessa forma eu perderia os recursos do componente como por exemplo mostrar a progressão do envio. Fiz essa sugestão porque o serviço rest do protheus não manipula o post de multipart/form-data corretamente, sendo necessário fazer o parsing manualmente e caso fosse enviado o arquivo em base64, a manipulação dos dados seria feita normalmente pelo serviço.

**Comment by jhosefmarks** [comment]
Nesse caso é necessário fazer a correção do lado do servidor, pois como você já citou isso degrada a requisição e não é a forma correta de fazer.

O progresso de envio funciona por que é usada a forma correta de envio de arquivos, se fizer do jeito que você está sugerindo não teríamos como ter o progresso parcial do envio como temos atualmente.
