### ISSUE TITLE
Ícones não são exibidos na linha da table

### ISSUE THREAD

**Issue by likid** [portinariui/portinari-angular#183]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

https://stackblitz.com/edit/portinariui-wahf1t

Passos para reproduzir:
1. Inserir o componente po-table no template.
2. Configurar alguma coluna da table para exibir ícones

#### Qual o comportamento atual?
O ícone não é exibido a menos que seja retirado a propriedade 'value' da configuração dos ícones, porém a propriedade é obrigatória e gera erro de compilação.

#### Que comportamento você esperava ver?
Exibir os ícones mesmo que fosse removido a propriedade 'icon' para utilizar o valor da propriedade 'value', porém nem mesmo assim o ícone é exibido.

#### Ambiente

- Portinari: 1.18.0
- Angular: 8.3.20
- Browser(s): Chrome 78
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 v1903

**Comment by jhosefmarks** [comment]
@likid para colunas do tipo `icon` você deve configurar o tipo de ícone para cada valor da sua coluna, ou seja, os ícones serão exibidos de acordo com o valor de cada linha exibida na tabela.

Esse é o comportamento do coluna de ícones.

**Comment by likid** [comment]
@jhosefmarks na minha aplicação, eu fiz uma configuração de coluna com ícone da seguinte forma:
```
{
      property: 'acao',
      label: 'Ação',
      type: 'icon',
      width: '10%',
      icons: [
        {
          action: this.removeAnexo.bind(this),
          icon: 'po-icon-delete',
          tooltip: 'Exclui o anexo',
          value: 'excluir'
        }
      ] 
}
```
e dessa forma funciona até a versão 1.16.0. Quando eu atualizei para a versão 1.17.0 e depois 1.18.0 o ícone passou a não ser mais exibido, exceto se eu remover a propriedade ```value```, porém gera erro de compilação. Se eu remover a propriedade ```icon``` e deixar apenas o ```value``` com valor ```po-icon-delete``` o ícone também não é exibido.

**Comment by jhosefmarks** [comment]
@likid isso era um bug que foi gerado em um refactory na versão [1.13.0](https://github.com/portinariui/portinari-angular/blob/master/CHANGELOG.md#1130-2019-10-18), e corrigido na versão [1.17.0](https://github.com/portinariui/portinari-angular/blob/master/CHANGELOG.md#1170-2019-11-25).

O comportamento atual é o comportamento normal desde sempre.

Baseado no seu exemplo, você precisa ter uma propriedade chamada `acao` com o valor 'excluir' na linha que você quer que seja exibido o ícone.

**Comment by likid** [comment]
Entendi, vou atualizar a biblioteca aqui novamente e testar. Valeu.

**Comment by jhosefmarks** [comment]
Se você quer uma ação configurada para todas as suas linhas usa a propriedade `p-actions` da tabela.

Ela vai ser sempre exibida independente dos valores da linha.
