### ISSUE TITLE
Botão com cursor pointer

### ISSUE THREAD

**Issue by OfficialMarinho** [portinariui/portinari-angular#201]
#### Descrição da melhoria
O affordance dos botões poderia ser melhorado adicionando o cursor pointer como padrão no componente.

#### Caso de uso
Usuários podem não identificar o botão ao navegar numa aplicação que utiliza o Portinari UI. A reação dos elementos com o cursor pode ser até mais importante que um simples hover.

**Comment by jhosefmarks** [comment]
Sugestão anotada!!!

**Comment by OfficialMarinho** [comment]
> Sugestão anotada!!!

Massa! Espero poder ajudar
