### ISSUE TITLE
PoPageBackgroundComponent não esta documentado no site 

### ISSUE THREAD

**Issue by andredealmei** [portinariui/portinari-angular#223]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

Passos para reproduzir:
1. 
2. 

#### Ambiente

- Portinari:
- Angular:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jhosefmarks** [comment]
Atualmente, o PoPageBackgroundComponent esse é um componente interno.
