### ISSUE TITLE
Bug ao Utilizar Ngtemplate na po-table

### ISSUE THREAD

**Issue by DiegoAbelTOTVS** [portinariui/portinari-angular#241]
#### Reprodução

https://stackblitz.com/edit/portinariui-n2comt

Observação: Identificamos que o problema começou a partir da versão 1.14.0 do @portinari/portinari-ui

Passos para reproduzir:
1. Criar uma table
2. Utilizar ng-template

![image](https://user-images.githubusercontent.com/44578105/72637334-cf306680-393f-11ea-8ba2-77cc80d9558a.png)

#### Qual o comportamento atual?
Não cria uma coluna para o componente que expande o box com as informações

#### Que comportamento você esperava ver?
Criar uma coluna para não ocupar a coluna setada como primeira na table

#### Ambiente

- Portinari: 1.22.2
- Angular: ~8.0.0
- Browser(s): Google Chrome, Versão 79.0.3945.117 (Versão oficial) 64 bits
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jhosefmarks** [comment]
@DiegoAbelTOTVS remova a propriedade `p-hide-detail` ou mude o valor para `false`.

**Comment by DiegoAbelTOTVS** [comment]
> @DiegoAbelTOTVS remova a propriedade `p-hide-detail` ou mude o valor para `false`.

Funcionou, obrigado pelo apoio.
