### ISSUE TITLE
Pegar os dados do Dynamic Form

### ISSUE THREAD

**Issue by Smmartinez** [portinariui/portinari-angular#253]
Galera, como faço para pegar os dados que estão dentro do Dynamic Form? Para fazer um PUT ou POST?
Eu já montei toda a lógica de carregamento da página, com o preenchimento de alguns dados que preciso e alguns que são preenchidos no formulário, mas não estou conseguindo pegar o formulário.
Meu HTML esta assim:
<div class="po-wrapper-menu-panel">
  <po-page-default [p-title]="title" [p-actions]="actionsBoletins">
    <po-dynamic-form #dynamicFormBoletins [p-fields]="boletimfields" [p-value]="boletimvalue">
    </po-dynamic-form>
  </po-page-default>
</div>
Tenho um botão de confirmar dentro do actionsBoletins, como pego todo esse conteúdo e envio para o meu POST?

**Comment by Smmartinez** [comment]
Não sei se é a forma mais correta mas eu mudei um pouco a lógica eu criei botões no formulário, e passei uma função no click do botão e passei dynamicForm.form.value como parâmetro e desta forma consegui pegar o valor.

**Comment by jhosefmarks** [comment]
Você também pode usar a propriedade p-value, que vai ter dar o objeto mais "clean".

**Comment by Smmartinez** [comment]
E como eu poderia pegar a propriedade ? Pegaria no evento ou pelo typescript?

**Comment by Smmartinez** [comment]
Passei assim confirmar([boletimvalue]) onde boletim é o meu p-valeu... e ele somente retorna o que teve alteração no formulário
