### ISSUE TITLE
Informações da tabela não carregam

### ISSUE THREAD

**Issue by Thamiresvs** [portinariui/portinari-angular#266]
https://portinari.io/documentation/po-page-dynamic-table

No exemplo a cima as informações não carregam e com isso dificulta a aprendizagem

**Comment by jhonyeduardo** [comment]
Bom dia @Thamiresvs 

Por favor acesse novamente e veja se estão carregando.

Nossa API de dados para exemplo não estava retornando-os.

Recentemente criamos um novo serviço para isto https://github.com/portinariui/portinari-sample-api porém não repassamos tudo ainda.

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Em breve teremos um material bem completo sobre uso dos componentes dinâmicos e dos templates.
