### ISSUE TITLE
Problema ao carregar Módulo de Login.

### ISSUE THREAD

**Issue by heltondenis** [portinariui/portinari-angular#292]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

#### Qual o comportamento atual?

Módulo de login não está sendo importando (PoPageLoginModule)

#### Que comportamento você esperava ver?

Esperava o carregamento do mesmo.

#### Ambiente

- Portinari: 
- Angular: 9
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jhonyeduardo** [comment]
Bom dia Helton,
Você não informou a URL/imagem do erro.

Entretanto, certifique-se se você instalou @portinari/portinari-templates e importou o módulo PoTemplatesModule.

Qualquer dúvida estou a disposição.
