### ISSUE TITLE
Apis passadas diretamente  pelas propriedade no PoPageDynamicService, não são interceptadas.

### ISSUE THREAD

**Issue by silverio27** [portinariui/portinari-angular#297]
Na minha aplicação armazeno localmente o token. 
Crio um HTTTP_INTERCEPTOR para injetar esse token no header de toda requisição HttpClient. Quando chamo as requisições na "mão" através do serviço HttpCliente, fica tudo certo, porém ao chamar pelas propriedade [p-service-api], o erro 401 é informado no debug console (vscode) e tb não é invocado o notification do erro.
Esta faltando algo que eu possa fazer?

**Comment by jhosefmarks** [comment]
Boa tarde @silverio27,

Você adicionou o seu interceptor no mesmo módulo que você adicionou o PoTemplatesModule?

**Comment by silverio27** [comment]
Oi @jhosefmarks ,
era isso meu interceptor estava no modulo principal, pq meus services ficam lá. Coloquei os provider interceptor pro mesmo modulo e deu certo. o Componente era o Page Dynamic Table. 
Obrigado!

**Comment by jhosefmarks** [comment]
Show @silverio27, que bom que deu certo.
