### ISSUE TITLE
Erro ao gerar Build --prod

### ISSUE THREAD

**Issue by caiadofelipe** [portinariui/portinari-angular#32]
Bom dia

Quando gero a build com --prod está ocorrendo o erro abaixo.

O mesmo erro não acontece quando gero a build do dev.

ERROR in node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoCalendarComponent.html(45,11): Property 'displayMonthNumber' is protected and only accessible within class 'PoCalendarBaseComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoCalendarComponent.html(47,17): Property 'displayMonthNumber' is protected and only accessible within class 'PoCalendarBaseComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoCalendarComponent.html(70,11): Property 'currentYear' is protected and only accessible within class 'PoCalendarBaseComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoCalendarComponent.html(72,17): Property 'currentYear' is protected and only accessible within class 'PoCalendarBaseComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoCalendarComponent.html(71,11): Property 'displayMonthNumber' is protected and only accessible within class 'PoCalendarBaseComponent' and its subclasses.
(1,1): Directive PoChartComponent, Expected 0 arguments, but got 1.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵcq.html(45,9): Property 'displayMonthNumber' is private and only accessible within class 'PoCalendarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵcq.html(46,17): Property 'displayMonthNumber' is private and only accessible within class 'PoCalendarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵcq.html(70,9): Property 'currentYear' is private and only accessible within class 'PoCalendarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵcq.html(71,17): Property 'currentYear' is private and only accessible within class 'PoCalendarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵcq.html(69,9): Property 'displayMonthNumber' is private and only accessible within class 'PoCalendarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoDatepickerRangeComponent.html(44,39): Expected 0 arguments, but got 1.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoRadioGroupComponent.html(17,9): Property 'readonly' does not exist on type 'PoRadioGroupComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(53,13): Property 'stopUpload' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(60,13): Property 'uploadFiles' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(39,17): Property 'getPoIcon' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(39,62): Property 'getFileSize' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(44,13): Property 'isStatusFile' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(44,13): Property 'isStatusFile' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(51,13): Property 'isStatusFile' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(58,13): Property 'isStatusFile' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(72,7): Property 'hasAnyFileUploading' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoUploadComponent.html(74,7): Property 'uploadFiles' is protected and only accessible within class 'PoUploadComponent' and its subclasses.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(15,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(24,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(33,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(11,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(19,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageEditComponent.html(28,9): Property 'parentContext' is private and only accessible within class 'PoPageEditComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoPageListComponent.html(53,13): Property 'parentRef' is private and only accessible within class 'PoPageListComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵfa.html(46,7): Property 'index' does not exist on type 'PoSlideItemComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoTableComponent.html(178,13): Property 'validateTableAction' is private and only accessible within class 'PoTableComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoToolbarComponent.html(16,7): Property 'userSrc' does not exist on type 'PoToolbarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoToolbarComponent.html(16,7): Property 'userName' does not exist on type 'PoToolbarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.PoToolbarComponent.html(17,7): Property 'userActions' does not exist on type 'PoToolbarComponent'.
node_modules/@portinari/portinari-ui/portinari-portinari-ui.d.ts.ɵef.html(8,5): Expected 2 arguments, but got 0.

**Comment by RafaellyG** [comment]
Boa tarde Felipe!

Ajustamos este problema em nossa sprint atual (Pataxó), acompanhe as nossas release notes pois em breve lançaremos esta correção.

Obrigada.
