### ISSUE TITLE
THF Kendo Chart

### ISSUE THREAD

**Issue by caiadofelipe** [portinariui/portinari-angular#34]
Boa tarde.

Gostaria de saber se no Portinari existe algum componente que faça o que o Kendo Chart faz no THF, o Chart é muito limitado e só tem a opção do tipo pizza.

**Comment by Isabelalvarenga** [comment]
Boa tarde!

Infelizmente hoje temos apenas o pie chart disponível na comunidade.
Porém, entendemos sua necessidade e manteremos esta issue em aberto para que o PO avalie a implementação de melhorias voltadas à parte de charts.   ;)

Se desejar, pode acompanhar nossas entregas através dos seguintes canais:
- Reviews públicas: acontecem à cada 15 dias, próxima sexta-feira (09/08/2019), às 14hrs, via webex: https://totvs.webex.com/totvs/j.php?MTID=m34071d6223a1b73e95450a8530550d3d
- Portal: http://portinari.io/

Qualquer dúvida, estamos à disposição!
Time THF

**Comment by caiadofelipe** [comment]
Boa tarde Isabela,

Posso utilizar o componente Char Kendo do THF junto com o PO?
Se puder já me ajuda.

**Comment by paulogabrielfs** [comment]
@caiadofelipe Após migrar para o Portinari, meu projeto continuou o componete THF-KENDO instalado, apenas precisei fazer uma alteração manual nas propriedades do kendo (Ex: [T-TYPE]) já que a migração alterou as propriedades para [P-XXXX]... passando essa alteração os componentes THF-KENDO funcionaram normalmente com o PO.

**Comment by caiadofelipe** [comment]
@paulogabrielfs, quando abri a issue eu já tinha efetuado o teste e vi realmente que funcionou, abrir essa issue mais para saber se poderia utilizar realmente e se não daria nenhum problema no futuro.
Tive a resposta oficial do pessoal do PO e o que me informaram é que futuramente não funcionará mais, então recomendo não usar.
Eles tem uma review toda semana e colocaram esse assunto em pauta na próxima para verificar a possibilidade de incluir algo parecido com esse componente no PO.

**Comment by jhonyeduardo** [comment]
Boa tarde @caiadofelipe 

Neste segundo semestre, vamos trabalhar para liberar o Donut, Gauge e Radar.

Portanto, caso tenha necessidade de urgência pode utilizar o thf-kendo, claro que verificando a licença, e depois utilizar o gráfico do próprio Portinari.

Caso queira contribuir fica a vontade :)

Qualquer dúvida estou a disposição!
