### ISSUE TITLE
Erro ao gerar Build --prod

### ISSUE THREAD

**Issue by danielsilvalima1996** [portinariui/portinari-angular#38]
**Boa tarde, Galera!**

Eu utilizava o THF e realizei a migração para Portinari.

Eu estou com problema ao tentar gerar o _**build**_ da aplicação Portinari, utilizando o seguinte código:
`ng build --prod --aot --sourceMap=false`

Entretanto ele gera o erro:

_Schema validation failed with the following errors:
  Data path ".budgets[1].type" should be equal to one of the allowed values._

Por gentileza, poderiam me auxiliar?

**Comment by jhonyeduardo** [comment]
Boa tarde Daniel,

Poderia atualizar a versão do Portinari para 1.5.0 para ver se o problema ainda ocorre?

Fico no aguardo.

**Comment by danielsilvalima1996** [comment]
Bom dia, Jhony!

atualizei o projeto e o erro foi corrigido.

Muito obrigado, Abraço!

**Comment by jhonyeduardo** [comment]
Show de bola Daniel,
Qualquer dúvida estamos a disposição, valeu!
