### ISSUE TITLE
Alinhamento de botões

### ISSUE THREAD

**Issue by raulti** [portinariui/portinari-angular#61]
Preciso alinhar dois botões a direita da tela, porém não encontrei nada na documentação, alguém pode me ajudar?

**Comment by jhonyeduardo** [comment]
Boa tarde @raulti 

Pode ser feito de algumas formas, veja algumas delas:
1. Utilizando po-pull-right, onde posiciona a div a direita do 'container' onde estiver inserido.

`<po-page-default p-title="Alinhando botões">

  <div class="po-pull-right">
    <po-button class="po-sm-6" p-label="Botão 1">
    </po-button>
    <po-button class="po-sm-6" p-label="Botão 2">
    </po-button>
  </div>

</po-page-default>
`

2. Utilizando classes de grid system:

`<po-page-default p-title="Alinhando botões">

   <div class="po-row">
    <div class="po-md-8">
      <po-input class="po-md-4"></po-input>
      <po-input class="po-md-4"></po-input>
    </div>

    <div class="po-md-4 po-pt-1">
      <po-button class="po-md-6" p-label="Botão 1"></po-button>
      <po-button class="po-md-6" p-label="Botão 2"></po-button>
    </div>
  </div>

</po-page-default>
`

Veja se é o que procura, qualquer coisa estou a disposição.

**Comment by raulti** [comment]
muito obrigado pela prestatividade e rapidez!
Aproveitando o tópico, o Portinari já tem table com paginação?

**Comment by jhonyeduardo** [comment]
De nada, precisando estamos ai.

O Table tem um botão de "Carregar mais resultados" onde pode ser realizado novas chamadas e atribuir seu resultado na tabela.

Podemos fechar esta issue?

**Comment by raulti** [comment]
Muito obrigado pela atenção e velocidade para responder!
