### ISSUE TITLE
Guia de estilo/css

### ISSUE THREAD

**Issue by Dadinel** [portinariui/portinari-angular#73]
Percebi que no [portal do Portinari](https://portinari.io/) não existe uma parte de guia em relação aos estilos/css do Portinari, sendo que já encontrei diversas classes css presentes no projeto de [style](https://github.com/portinariui/portinari-style) do Portinari, contendo por exemplo as cores utilizadas nos componentes, acho que seria legal ter esse guia ou uma lista de classes css para que possamos seguir o mesmo estilo já presente nos componentes.

**Comment by nicoleoliveira** [comment]
Olá @Dadinel,

atualmente nós temos algumas documentações destas classes disponíveis nos nossos [guias](https://portinari.io/guides/), mas sabemos que ainda não estão todas documentadas.

O nosso planejamento é terminar a documentação dos temas ainda neste ano e no ano que vem iniciarmos a documentação para este guia de estilos. 

Agradecemos o contato!
Ainda tem alguma dúvida sobre este assunto?

**Comment by mateusjmaf** [comment]
Olá @Dadinel,

Gostaríamos de saber, as dúvidas pertinentes à esta ISSUE foram atendidas?

> Salientamos que ISSUES com 35 dias ou mais sem interação serão encerradas.

Estamos à disposição.

Atenciosamente,
Mateus J. | Portinari UI

**Comment by Dadinel** [comment]
Boa tarde,

Não sei, já existe um lugar que eu possa consultar as classes CSS em relação por exemplo as cores do Portinari não sendo o próprio repositório? Se sim, acredito que possa ser encerrada, ou isso fica pendente de ser feito e a issue é encerrada mesmo assim?

**Comment by jhosefmarks** [comment]
Olá @Dadinel,

Para criação de temas, logo teremos uma documentação explicando passo a passo como você pode criar seu próprio tema para o Portinari UI.

Sobre o uso das classes, temos algumas documentações específicas que você pode usar:

- [Grid System](https://portinari.io/guides/grid-system)
- [Espaçamento](https://portinari.io/guides/spacing)
- [Biblioteca de ícones](https://portinari.io/guides/icons)

Demais classes não foram isoladas e não recomendamos o uso pois podem sofrer quebras sem aviso prévio, pois hoje o Portinari UI não tem como objetivo ser um framework CSS isolado.

Estamos estudando ter um Design System documentado e aberto no futuro, mas isso é um papo mais lá pra frente.

Espero ter respondido suas dúvidas.
