### ISSUE TITLE
Incluir possibilidade de definir a duração de notificações

### ISSUE THREAD

**Issue by guiebitt** [portinariui/portinari-angular#89]
Permitir que as notificações do serviço PoNotificationService, possam ser definidas informando um tempo de duração definido pelo usuário, não utilizando o padrão de 10 segundos.
Permitir também ter uma forma de definição da duração padrão para todas as notificações.

#90

**Comment by Rogerio-Fialho** [comment]
Boa tarde,

O item foi incluído em nosso backlog e será priorizado pelo PO conforme a demanda.

**Comment by guiebitt** [comment]
Olá Rogério, obrigado. Abri o PR #90 em relação a este item.
